CS50Web_QuizProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizes.urls', namespace='quizes')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizes/urls.py
from django.urls import path
from .views import (
  QuizListView,
  quiz_view,
  quiz_data_view,
  save_quiz_view
)

app_name = 'quizes'

urlpatterns = [
  path('', QuizListView.as_view(), name='main-view'),
  path('<pk>/', quiz_view, name='quiz-view'),
  path('<pk>/save/', save_quiz_view, name='save-view'),
  path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
]

questions/models.py
from django.db import models
from quizes.models import Quiz
# Create your models here.

class Question(models.Model):
  text = models.CharField(max_length=255)
  quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
  created = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return str(self.text)
  
  def get_answers(self):
    return self.answer_set.all()

class Answer(models.Model):
  text = models.CharField(max_length=200)
  correct = models.BooleanField(default=False)
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  created = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"

quizes/models.py
from django.db import models
import random

DIFF_CHOICES = (
  ('easy', 'easy'),
  ('medium', 'medium'),
  ('hard', 'hard')
)

class Quiz(models.Model):
  name = models.CharField(max_length=120)
  topic = models.CharField(max_length=120)
  number_of_questions = models.IntegerField()
  time = models.IntegerField(help_text="duration of the quiz in minutes")
  required_score_to_pass = models.IntegerField(help_text="required score to pass in %")
  difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES)

  def __str__(self):
    return f"{self.name}-{self.topic}"
  
  def get_questions(self):
    questions = list(self.question_set.all())
    random.shuffle(questions)
    return questions[:self.number_of_questions]
  
  class Meta:
   verbose_name_plural = 'Quizes'

results/models.py
from django.db import models
from quizes.models import Quiz
from django.contrib.auth.models import User

# Create your models here.

class Result(models.Model):
  quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  score = models.FloatField()

  def __str__(self):
    return str(self.pk)

questions/views.py
from django.shortcuts import render

# Create your views here.

quizes/views.py
from django.shortcuts import render
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse, HttpResponseBadRequest
from questions.models import Question, Answer
from results.models import Result
from django.shortcuts import get_object_or_404

class QuizListView(ListView):
  model = Quiz
  template_name = 'quizes/main.html'

def quiz_view(request, pk):
  quiz = Quiz.objects.get(pk=pk)
  return render(request, 'quizes/quiz.html', {'obj': quiz})

def quiz_data_view(request, pk):
  quiz = Quiz.objects.get(pk=pk)
  questions = quiz.get_questions()
  answers_data = []
  for q in questions:
    answer_options = []
    for a in q.answer_set.all():
      answer_options.append(a.text)
    answers_data.append({str(q): answer_options})
  return JsonResponse({
    'data': answers_data,
    'time': quiz.time,
  })

def save_quiz_view(request, pk):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        print("AJAX request received.")
        questions = []
        data = request.POST
        data_ = dict(data.lists())
        
        data_.pop('csrfmiddlewaretoken', None)
        
        print("Data received:", data_)
        
        for k in data_.keys():
            question = get_object_or_404(Question, text=k)
            questions.append(question)
        
        user = request.user
        quiz = get_object_or_404(Quiz, pk=pk)
        
        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        
        for q in questions:
            a_selected = data.get(q.text)
            
            if a_selected is not None:
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text
                
                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})
        
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)
        
        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})
    else:
        return HttpResponseBadRequest("This is not an AJAX request")

results/views.py
from django.shortcuts import render

# Create your views here.

quizes/templates/quizes/main.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
  <script src="{% static 'quizes/main.js' %}" defer></script>
  <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock scripts %}

{% block title %}
Home
{% endblock title %}

{% block content %}

  <!-- Modal -->
  <div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Start?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="modal-body-confirm"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-bs-dismiss="modal">No</button>
          <button type="button" id="start-button" class="btn btn-success">Yes</button>
        </div>
      </div>
    </div>
  </div>

  <div class="home-title h1 fw-bolder">Trivia Challenges</div>
  <hr>

  <div class="row row-cols-1 row-cols-md-2 g-4">
    {% for obj in object_list %}
      <div class="col">
        <div class="card">
          <div class="card-body rounded-1">
            <h4 class="card-title fw-bolder">{{ obj.name }}</h4>
            <p class="card-text text-muted">Topic: {{ obj.topic }}</p>
            <p class="card-text text-muted">Difficulty: {{ obj.difficulty }}</p>
            <button
              class="btn btn-success modal-button"
              data-pk="{{ obj.pk }}"
              data-quiz="{{ obj.name }}"
              data-topic="{{ obj.topic }}"
              data-questions="{{ obj.number_of_questions }}"
              data-difficulty="{{ obj.difficulty }}"
              data-time="{{ obj.time }}"
              data-pass="{{ obj.required_score_to_pass }}"
              data-bs-toggle="modal"
              data-bs-target="#quizStartModal">
                Let's Go!
            </button><br>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

{% endblock content %}

quizes/templates/quizes/quiz.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
  <script src="{% static 'quizes/quiz.js' %}" defer></script>
  <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock scripts %}

{% block title %}
{{obj.name}}
{% endblock title %}


{% block content %}
  <div class="time-bar navbar sticky-top border border-black rounded-1">
    <div class="container-fluid">
      <div class="col">
        <b style="font-size: 22px;">{{obj.name}}</b>
        <p style="font-size: 18px;">Score to pass: {{obj.required_score_to_pass}}%</p>
      </div>
      <div class="col text-end" style="font-size: 26px;" id="timer-box"></div>
    </div>
    <a href="{% url 'quizes:main-view' %}" class="btn btn-warning m-2">Go back</a>
  </div>


  <form id="quiz-form" class="mt-3 mb-3" action="{% url 'quizes:save-view' obj.pk %}" method="POST">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <button type="submit" class="btn btn-success mt-3">Submit</button>
  </form>

  <div id="score-box"></div>
  <div id="result-box"></div>
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- favicon -->
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" /> 
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script> 
        <link rel="stylesheet" href="{% static 'style.css' %}">

        {% block scripts %}
        {% endblock scripts %}

        <title>Trivia Challenges! | {% block title %}{% endblock title %}</title>
    </head>
    <body>
        <div class="container mt-3">
            {% block content %}
            {% endblock content %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>

</html>